setGeneric("write.reduced", function(x,...) standardGeneric("write.reduced"))
setGeneric("reduced",       function(object) standardGeneric("reduced"))
setGeneric("reduced<-",     function(object, value) standardGeneric("reduced<-"))
setGeneric("loadings",       function(object) standardGeneric("loadings"))
setGeneric("loadings<-",     function(object, value) standardGeneric("loadings<-"))
setGeneric("exprs",       function(object) standardGeneric("exprs"))
setGeneric("exprs<-",     function(object, value) standardGeneric("exprs<-"))
# setGeneric("assignments",       function(object) standardGeneric("assignments"))
# setGeneric("assignments<-",     function(object, value) standardGeneric("assignments<-"))
# setGeneric("moduleNames",       function(object) standardGeneric("moduleNames"))
# setGeneric("moduleNames<-",     function(object, value) standardGeneric("moduleNames<-"))
setGeneric("factorNames",       function(object) standardGeneric("factorNames"))
setGeneric("factorNames<-",     function(object, value) standardGeneric("factorNames<-"))
setGeneric("nComponents",     function(object) standardGeneric("nComponents"))
setGeneric("nSamples",     function(object) standardGeneric("nSamples"))
setGeneric("nFeatures",     function(object) standardGeneric("nFeatures"))
