
setGeneric("reduced", function(x, ...) standardGeneric("reduced"))
setGeneric("reduced<-", function(x, value) standardGeneric("reduced<-"))
setGeneric("loadings", function(x, ...) standardGeneric("loadings"))
setGeneric("loadings<-", function(x, value) standardGeneric("loadings<-"))
setGeneric("varexp", function(x) standardGeneric("varexp"))
setGeneric("varexp<-", function(x, value) standardGeneric("varexp<-"))
setGeneric("componentNames", function(x) standardGeneric("componentNames"))
setGeneric("componentNames<-", function(x, value) standardGeneric("componentNames<-"))
setGeneric("sampleNames", function(x) standardGeneric("sampleNames"))
setGeneric("featureNames", function(x) standardGeneric("featureNames"))
setGeneric("project_data", function(x, newdata, ...) standardGeneric("project_data"))
setGeneric("assignments",       function(x, ...) standardGeneric("assignments"))
setGeneric("assignments<-",     function(x, value) standardGeneric("assignments<-"))
setGeneric("moduleNames",       function(x, ...) standardGeneric("moduleNames"))
setGeneric("moduleNames<-",     function(x, value) standardGeneric("moduleNames<-"))
setGeneric("nComponents",     function(x) standardGeneric("nComponents"))
setGeneric("nSamples",     function(x) standardGeneric("nSamples"))
setGeneric("nFeatures",     function(x) standardGeneric("nFeatures"))
setGeneric("getGeneIDs",     function(x, ...) standardGeneric("getGeneIDs"))
setGeneric("getAlignedFeatures",     function(x, ...) standardGeneric("getAlignedFeatures"))
setGeneric("runEnrich",     function(x, ...) standardGeneric("runEnrich"))
