#' ModularExperiment: A container for the results of module analysis
#'
#' @description
#' A container inheriting from \link[ReducedExperiment]{ReducedExperiment}, that
#' contains one or more data matrices, to which module analysis has been applied
#' to identify a reduced set of features.
#'
#' @param reduced A data matrix, produced by module analysis, with rows
#' representing samples and columns representing module expression profiles.
#' Typically, this matrix contains "eigengenes" produced by the Weighted Gene
#' Correlation Network Analysis Approach, as is applied by
#' \link[ReducedExperiment]{identify_modules}.
#'
#' @param assignments A vector of features, named according to the module to which the
#' feature belongs.
#'
#' @param loadings A numeric vector representing the loadings used to generate
#' module expression profiles. Typically, these values are obtained from the
#' rotation matrix produced by \link[stats]{prcomp}, which is used to identify
#' the first principal component of each module. The vector names represent
#' features.
#'
#' @param scale Either a boolean, representing whether or not the original data
#' has been scaled to unit variance, or a numeric vector indicating the
#' standard deviations of the original features (as produced by
#' \link[base]{scale}.)
#'
#' @param center Either a boolean, representing whether or not the original data
#' has been centered to have a mean of 0, or a numeric vector indicating the
#' means of the original features (as produced by
#' \link[base]{scale}.)
#'
#' @param dendrogram Either NULL, or the dendrogram used to identify modules from the
#' original data.
#'
#' @param threshold Either NULL, or a matrix produced by
#' \link[WGCNA]{pickSoftThreshold} indicating the parameters used for network
#' construction.
#'
#' A class to represent the results of module analysis
#'
#' @import SummarizedExperiment
#'
#' @export
ModularExperiment <- function(loadings=numeric(), assignments=character(), dendrogram=NULL, threshold=NULL, ...)
{
    re <- ReducedExperiment(...)
    return(.ModularExperiment(re, loadings=loadings, assignments=assignments, dendrogram=dendrogram, threshold=threshold))
}

S4Vectors::setValidity2("ModularExperiment", function(object) {
    msg <- NULL

    obj_dims <- dim(object)

    # Assignments
    if (obj_dims[1] != length(assignments(object)))
        msg <- c(msg, "Assignments have invalid length")

    if (!all(assignments(object) == rownames(object)))
        msg <- c(msg, "Assignments have incompatible names (rownames)")

    # Loadings
    if (obj_dims[1] != length(loadings(object)))
        msg <- c(msg, "Loadings have invalid length")

    if (!all(names(loadings(object)) == rownames(object)))
        msg <- c(msg, "Loadings have incompatible names (rownames)")

    return(if (is.null(msg)) TRUE else msg)
})

#' Get and set module feature assignments
#'
#' Retrieves a vector of features (usually genes) named by the modules
#' they belong to.
#'
#' The assignments can be modified with `<-`.
#'
#' @param object \link[ReducedExperiment]{ModularExperiment} object.
#'
#' @param as_list If `TRUE`, the results are returned as a list, with an entry
#' for each module containing a list of features.
#'
#' @rdname module_assignments
#' @export
setMethod("assignments", "ModularExperiment", function(object, as_list=FALSE) {
    if (as_list)  {
        a <- list()
        for (comp in componentNames(object)) {
            a[[comp]] <- assignments(object)[which(names(assignments(object)) == comp)]
        }
    } else {
        a <- object@assignments
    }

    return(a)
})

#' @rdname module_assignments
#' @export
setReplaceMethod("assignments", "ModularExperiment", function(object, value) {
    object@assignments <- value
    validObject(object)
    return(object)
})

#' Get and set modules loadings
#'
#' Retrieves the module loadings as a vector, with a value for each feature
#' (usually genes).
#'
#' The loadings can be modified with `<-`.
#'
#' @param object \link[ReducedExperiment]{ModularExperiment} object.
#'
#' @param scale_loadings If `TRUE`, loadings will be scaled column-wise to have a
#' standard deviation of 0.
#'
#' @param center_loadings If `TRUE`, loadings will be centered column-wise to have a mean
#' of 0.
#'
#' @param abs_loadings If `TRUE`, the absolute values of the loadings will be
#' returned.
#'
#' @details
#' When available, the module loadings provide the values of the rotation matrix
#' (usually generated by \link[stats]{prcomp}) used to calculate the
#' sample-level module vectors available in the `reduced` slot. Normally, these
#' loadings are calculated for each module separately, so their values are
#' not comparable across modules.
#'
#'
#' @rdname module_loadings
#' @export
setMethod("loadings", "ModularExperiment", function(object, scale_loadings=FALSE, center_loadings=FALSE, abs_loadings=FALSE) {
    l <- scale(object@loadings, scale=scale_loadings, center=center_loadings)
    if (abs_loadings) l <- abs(l)
    return(l[,1])
})

#' @rdname module_loadings
#' @export
setReplaceMethod("loadings", "ModularExperiment", function(object, value) {
    object@loadings <- value
    validObject(object)
    return(object)
})

#' @rdname feature_names
#' @export
setReplaceMethod("names", "ModularExperiment", function(x, value) {
    object <- x

    object@assignments <- stats::setNames(value, names(object@assignments))
    object@loadings <- stats::setNames(object@loadings, value)

    object <- callNextMethod(object, value)
    validObject(object)

    return(object)
})

#' @rdname feature_names
#' @export
setReplaceMethod("featureNames", "ModularExperiment", function(object, value) {
    names(object) <- value
    return(object)
})

#' @rdname feature_names
#' @export
setReplaceMethod("rownames", "ModularExperiment", function(x, value) {
    object <- x

    names(object) <- value
    return(object)
})

#' @rdname component_names
#' @export
setReplaceMethod("componentNames", "ModularExperiment", function(object, value) {

    curr_names <- colnames(object@reduced)
    object <- callNextMethod(object, value)
    new_names <- colnames(object@reduced)

    for (i in 1:length(curr_names)) {
        names(object@assignments)[which(names(object@assignments) == curr_names[i])] <- new_names[i]
    }

    validObject(object)
    return(object)
})

#' @rdname component_names
#' @export
setMethod("moduleNames", "ModularExperiment", function(object) {
    return(componentNames(object))
})

#' @rdname component_names
#' @export
setReplaceMethod("moduleNames", "ModularExperiment", function(object, value) {
    componentNames(object) <- value
    return(object)
})

#' @rdname individual_dims
#' @export
setMethod("nModules", "ModularExperiment", function(object) {dim(object)[3]})

#' Get the dendrogram stored in a ModularExperiment
#'
#' @param object \link[ReducedExperiment]{ModularExperiment} object.
#'
#' @export
setMethod("dendrogram", "ModularExperiment", function(object) {
    return(object@dendrogram)
})

setReplaceMethod("dendrogram", "ModularExperiment", function(object, value) {
    object@dendrogram <- value
    return(object)
})

#' Required for dollarsign autocomplete of colData columns
.DollarNames.ModularExperiment <- function(x, pattern = "")
    grep(pattern, names(colData(x)), value=TRUE)

#' @rdname slice
#' @export
setMethod("[", c("ModularExperiment", "ANY", "ANY", "ANY"),
          function(x, i, j, k, ..., drop=FALSE)
{
    object <- x

    if (1L != length(drop) || (!missing(drop) && drop))
        warning("'drop' ignored '[,", class(object), ",ANY,ANY-method'")

    assignments <- object@assignments
    lod <- object@loadings

    if (!missing(i)) {
        if (is.character(i)) {
            fmt <- paste0("<", class(object), ">[i,] index out of bounds: %s")
            i <- SummarizedExperiment:::.SummarizedExperiment.charbound(
              i, rownames(object), fmt
            )
        }

        i <- as.vector(i)
        assignments <- assignments[i, drop=FALSE]
        lod <- lod[i, drop=FALSE]
    }

    out <- callNextMethod(object, i, j, k, ...)
    BiocGenerics:::replaceSlots(out, loadings=lod, assignments=assignments, check=FALSE)
})

# Same features, different samples
#' @rdname cbind
#' @export
setMethod("cbind", "ModularExperiment", function(..., deparse.level=1) {
    args <- list(...)

    loadings_assignments_equal <- sapply(args, function(re) {
        return(identical(re@loadings, args[[1]]@loadings) & identical(re@assignments, args[[1]]@assignments))
    })

    if (!all(loadings_assignments_equal))
        stop("Row bind expects loadings and assignments slots are equal")

    args[["deparse.level"]] <- deparse.level

    return(do.call(callNextMethod, args))
})

#' @rdname enrichment
#' @export
setMethod("runEnrich", c("ModularExperiment"),
          function(object, method="overrepresentation", feature_id_col="rownames", as_dataframe=FALSE, ...)
{
    if (method == "overrepresentation") {

        if (feature_id_col != "rownames") names(object) <- rowData(object)[[feature_id_col]]

        modules <- assignments(object, as_list=TRUE)

        enrich_res <- reduced_oa(modules, ...)

    } else {
        stop("Enrichment method not recognised")
    }

    if (as_dataframe)  {
        enrich_res <- lapply(enrich_res, function(object) {object@result})
        enrich_res <- do.call("rbind", enrich_res)
    }

    return(enrich_res)
})

#' Plot a dendrogram stored in a ModularExperiment
#'
#' Gets the dendrogram and plots it using
#' \link[WGCNA]{plotDendroAndColors}.
#'
#' @param object \link[ReducedExperiment]{ModularExperiment} object.
#'
#' @param groupLabels Module label axis label.
#' See \link[WGCNA]{plotDendroAndColors}.
#'
#' @param If TRUE, shows feature names in the dendrogram.
#' See \link[WGCNA]{plotDendroAndColors}.
#'
#' @param hang See \link[WGCNA]{plotDendroAndColors}.
#'
#' @param addGuide See \link[WGCNA]{plotDendroAndColors}.
#'
#' @param guideHang See \link[WGCNA]{plotDendroAndColors}.
#'
#' @param color_func Function for converting module names to colors. Only used
#' if `modules_are_colors` is FALSE
#'
#' @param modules_are_colors If TRUE, expects the module names to be colors.
#' Else, assumes that module names are are numbers that can be converted into
#' colours by `color_func`.
#'
#' @export
setMethod("plotDendro", c("ModularExperiment"),
          function(object, groupLabels = "Module colors", dendroLabels = FALSE,
                       hang = 0.03, addGuide = TRUE, guideHang = 0.05,
                       color_func = WGCNA::labels2colors, modules_are_colors = FALSE) {

    if (!modules_are_colors) {
        colors <- as.numeric(gsub("module_", "", names(assignments(object))))
        colors <- color_func(colors)
    }

    WGCNA::plotDendroAndColors(dendrogram(object), colors,
                           groupLabels = groupLabels,
                           dendroLabels = dendroLabels, hang = hang,
                           addGuide = addGuide, guideHang = guideHang)
})

#' Project new data using pre-defined factors
#'
#' @description
#' Calculates eigengenes for modules in new data. If in `project` mode, functions
#' in a similar fashion to the `predict` method of \link[stats]{prcomp}. Else,
#' eigengenes are calculated from scratch using PCA, in a similar manner to the
#' \link[WGCNA]{moduleEigengenes} function.
#'
#' @param object A \link[ReducedExperiment]{ModularExperiment} object. The `loadings` slot of
#' this class will be used for projection. Additionally, by default, the `scale`
#' and `center` slots are used to apply the original transformation to the
#' new data.
#'
#' @param newdata New data for eigengenes to be calculates in. Must be a
#' `data.frame` or `matrix` with features as rows and samples as columns, or a
#' \link[SummarizedExperiment]{SummarizedExperiment} object. Assumes that the
#' rows of `newdata` match those of the \link[ReducedExperiment]{ModularExperiment}
#' object.
#'
#' @param project Whether to perform projection (i.e., using PCA rotation matrix
#' from the original data to calculate modules) or calculate eigengenes from
#' scratch in the new data (i.e., performing PCA for each module in `newdata`).
#'
#' @param scale_reduced Whether or not the reduced data should be scaled
#' after calculation.
#'
#' @param scale_newdata Controls whether the `newdata` are scaled. If NULL,
#' performs scaling based on the \link[ReducedExperiment]{ModularExperiment}
#' object's `scale` slot. The value of this argument will be passed to the
#' `scale` argument of \link[base]{scale}.
#'
#' @param center_newdata Controls whether the `newdata` are centered If NULL,
#' performs centering based on the \link[ReducedExperiment]{ModularExperiment}
#' object's `center` slot. The value of this argument will be passed to the
#' `center` argument of \link[base]{scale}.
#'
#' @param assay_name If a \link[SummarizedExperiment]{SummarizedExperiment}
#' object is passed as new data, this argument indicates which assay should be
#' used for projection.
#'
#' @param realign If `project` is TRUE, this argument is ignored. Else, controls
#' whether eigengenes are realigned after PCA is performed to ensure the resultant
#' signatures are positively correlated with average expression of the module.
#' Similar to the `align` argument of \link[WGCNA]{moduleEigengenes}.
#'
#' @param min_module_genes If `project` is FALSE, this argument is ignores. Else,
#' controls the minimum number of genes required in a module for projection. Projected
#' eigengenes are not calculated for modules with sizes below this threshold.
#'
#' @returns Calculates a matrix with samples as rows and modules as columns. If
#' `newdata` was a `matrix` or `data.frame`, this will be returned as a matrix.
#' If a \link[SummarizedExperiment]{SummarizedExperiment} object was passed
#' instead, then a If a \link[ReducedExperiment]{ModularExperiment}
#' object will be created containing this matrix in its `reduced` slot.
#'
#' @seealso [ReducedExperiment::projectData()], [WGCNA::moduleEigengenes()]
#'
#' @rdname calcEigengenes
#' @export
setMethod("calcEigengenes", c("ModularExperiment", "matrix"),
          function(object, newdata, project=TRUE, scale_reduced=TRUE, return_loadings=FALSE, scale_newdata=NULL, center_newdata=NULL, realign=TRUE, min_module_genes=10) {

    if (!identical(rownames(object), rownames(newdata)))
        stop("Rownames of x do not match those of newdata")

    # apply known vectors for scaling and centering (returned as attributes by `scale`)
    if (is.null(scale_newdata)) scale_newdata <- object@scale
    if (is.null(center_newdata)) center_newdata <- object@center

    newdata <- t(scale(t(newdata), scale=scale_newdata, center=center_newdata))

    if (project) {

        red <- .project_eigengenes(newdata, moduleNames(object), assignments(object), loadings(object), min_module_genes=min_module_genes)
        eigengenes <- list("reduced" = as.matrix(red), "loadings" = loadings(object))

    } else {

        eigengenes <- .calculate_eigengenes(newdata, moduleNames(object), assignments(object), realign=realign)
    }

    if (scale_reduced) eigengenes$red <- scale(eigengenes$red)

    if (return_loadings) {
        return(eigengenes)
    } else {
        return(eigengenes$red)
    }
})

#' @rdname calcEigengenes
#' @export
setMethod("calcEigengenes", c("ModularExperiment", "data.frame"), function(
        object, newdata, project=TRUE, scale_reduced=TRUE, return_loadings=FALSE,
        scale_newdata=NULL, center_newdata=NULL, realign=TRUE, min_module_genes=10) {

    return(calcEigengenes(object, as.matrix(newdata), project=project, return_loadings=return_loadings,
                          scale_newdata=scale_newdata, center_newdata=center_newdata, realign=realign,
                          scale_reduced=scale_reduced, min_module_genes=min_module_genes))
})

#' @rdname calcEigengenes
#' @export
setMethod("calcEigengenes", c("ModularExperiment", "SummarizedExperiment"),
          function(object, newdata, project=TRUE, scale_reduced=TRUE, assay_name="normal", scale_newdata=NULL, center_newdata=NULL, realign=TRUE, min_module_genes=10) {

    eig <- calcEigengenes(object, assay(newdata, assay_name), project=project, return_loadings=FALSE,
                          scale_newdata=scale_newdata, center_newdata=center_newdata, realign=realign,
                          scale_reduced=scale_reduced, min_module_genes=min_module_genes)

    return(.se_to_me(newdata, reduced=as.matrix(eig), loadings=loadings(object), assignments=assignments(object), center_X=object@center, scale_X=object@scale))
})

#' @rdname calcEigengenes
#' @export
setMethod("predict", c("ModularExperiment"), function(object, newdata, ...) {
    return(calcEigengenes(object, newdata, ...))
})

#' Get correlation of features with module eigengenes
#'
#' @param object \link[ReducedExperiment]{ModularExperiment} object.
#'
#' @param assay_name The name of the assay to be used for calculation of
#' module centrality.
#'
#' @param feature_id_col The column in `rowData(object)` that will be used as a
#' feature ID. Setting this to "rownames" (default) instead uses
#' `rownames(object)`.
#'
#' Results indicate correlation (r) and squared correlation (rsq) with the module eigengene. Feature ranks
#' within each module are also returned based on these statistics.
#'
#' @export
setMethod("getCentrality", c("ModularExperiment"), function(object, assay_name = "normal", feature_id_col = "rownames") {

    # Get module membership (correlation with eigengene)
    signed_kme <- WGCNA::signedKME(
        t(assay(object, assay_name)),
        reduced(object)
    )
    colnames(signed_kme) <- componentNames(object)

    stopifnot(all(rownames(signed_kme) == rownames(object)))
    if (feature_id_col != "rownames") rownames(signed_kme) <- rowData(object)[[feature_id_col]]

    # Transform into a dataframe with relevant statistics
    module_features <- data.frame()
    for (m in componentNames(object)) {

        which_features <- which(names(assignments(object)) == m)

        module_kme <- data.frame(
            module = m,
            feature = rownames(signed_kme)[which_features],
            r = signed_kme[[m]][which_features]
        )

        module_kme$rsq <- module_kme$r ** 2
        module_kme$rank_r <- rank(1 - module_kme$r)
        module_kme$rank_rsq <- rank(1 - module_kme$rsq)

        module_features <- rbind(module_features, module_kme)
    }

    module_features <- module_features[order(module_features$rsq, decreasing = TRUE) ,]
    module_features <- module_features[order(module_features$module) ,]

    return(module_features)
})
